spring:
  application:
    name: catalog-service

server:
  port: 8080

app:
  data:
    dir: ./data
  csv:
    charset: UTF-8
    delimiter: ','
    list-separator: ';'
    images-separator: '|'

management:
  endpoints:
    web:
      exposure:
        include: health,info
spring-doc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs